name: Release Helm Charts

on:
#   workflow_run:
#     workflows: ["Opensource Charts Validation yyyy"]
#     types:
#       - completed
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      chart-releaser:
        type: choice
        # Friendly description to be shown in the Release Helm Charts'
        description: 'Release Helm Charts'
        # Default value if no value is explicitly provided
        default: 'No'
        # Input has to be provided for the workflow to run
        required: true
        options:
        - 'Yes'
        - 'No'

jobs:
  release:
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' }}||
      ${{ github.event.inputs.chart-releaser == 'Yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.8.1
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.TOKEN }}"
